import React from 'react';
import { useForm } from '@inertiajs/react';

export default function Create() {
    const { data, setData, post, processing, errors } = useForm({
        tc_report_id: '', tc_report_type: '', tc_report_start_date: '', tc_report_end_date: '', tc_report_data: '', tc_generated_by: '', tc_created_at: ''
    });

    function handleSubmit(e) {
        e.preventDefault();
        post('/timecap-reports');
    }

    return (
        <div>
            <h1>Create New Timecap reports</h1>
            <form onSubmit={handleSubmit}>
                <div>
                    <label>Tc report id</label>
                    <input
                        value={data.tc_report_id}
                        onChange={e => setData('tc_report_id', e.target.value)}
                    />
                    {errors.tc_report_id && <div>{errors.tc_report_id}</div>}
                </div>
<div>
                    <label>Tc report type</label>
                    <input
                        value={data.tc_report_type}
                        onChange={e => setData('tc_report_type', e.target.value)}
                    />
                    {errors.tc_report_type && <div>{errors.tc_report_type}</div>}
                </div>
<div>
                    <label>Tc report start date</label>
                    <input
                        value={data.tc_report_start_date}
                        onChange={e => setData('tc_report_start_date', e.target.value)}
                    />
                    {errors.tc_report_start_date && <div>{errors.tc_report_start_date}</div>}
                </div>
<div>
                    <label>Tc report end date</label>
                    <input
                        value={data.tc_report_end_date}
                        onChange={e => setData('tc_report_end_date', e.target.value)}
                    />
                    {errors.tc_report_end_date && <div>{errors.tc_report_end_date}</div>}
                </div>
<div>
                    <label>Tc report data</label>
                    <input
                        value={data.tc_report_data}
                        onChange={e => setData('tc_report_data', e.target.value)}
                    />
                    {errors.tc_report_data && <div>{errors.tc_report_data}</div>}
                </div>
<div>
                    <label>Tc generated by</label>
                    <input
                        value={data.tc_generated_by}
                        onChange={e => setData('tc_generated_by', e.target.value)}
                    />
                    {errors.tc_generated_by && <div>{errors.tc_generated_by}</div>}
                </div>
<div>
                    <label>Tc created at</label>
                    <input
                        value={data.tc_created_at}
                        onChange={e => setData('tc_created_at', e.target.value)}
                    />
                    {errors.tc_created_at && <div>{errors.tc_created_at}</div>}
                </div>
                <button type="submit" disabled={processing}>Save</button>
            </form>
        </div>
    );
}
