import React from 'react';

export default function Show({ item }) {
    return (
        <div>
            <h1>Details of Timecap reports</h1>
            <p><strong>ID:</strong> {item.id}</p>
            <p><strong>Tc report id:</strong> {item.tc_report_id}</p>
<p><strong>Tc report type:</strong> {item.tc_report_type}</p>
<p><strong>Tc report start date:</strong> {item.tc_report_start_date}</p>
<p><strong>Tc report end date:</strong> {item.tc_report_end_date}</p>
<p><strong>Tc report data:</strong> {item.tc_report_data}</p>
<p><strong>Tc generated by:</strong> {item.tc_generated_by}</p>
<p><strong>Tc created at:</strong> {item.tc_created_at}</p>
        </div>
    );
}
